### ISSUE TITLE
Make virtual ftp user uid and gid configurable

### ISSUE THREAD

**Issue by trnubo** [panubo/docker-vsftpd#8]
Currently the virtual ftp user gid and uid is hard coded in the Dockerfile to 48:48.

This should be configurable so you can use what ever uid or gid you like (except maybe root 0:0).

I see two options
1) Make the uid and gid configurable via build args
2) Make the uid and gid configurable at run time by creating the ftp user in the entry.sh file

**Comment by RichardBronosky** [comment]
I would favor the 2nd option since it will prevent you from having to push N containers to your internal repo if you need N different user IDs (in different containers of course).
It's entirely possible because:
* The vsftpd.conf specifies only the name of the user on line 30 https://github.com/panubo/docker-vsftpd/blob/master/vsftpd.conf#L30
* Even though the user is created early on line 3, it is never used in the Dockerfile. https://github.com/panubo/docker-vsftpd/blob/master/Dockerfile#L3

I guess the only question is whether to put it inside or outside of the `if [ "$1" == "vsftpd" ]` conditional on line 40
https://github.com/panubo/docker-vsftpd/blob/master/entry.sh#L40

**Comment by trnubo** [comment]
The latest update has support for setting the UID and GID with Docker build args. We still might look at having this configurable at runtime in the future. Closing for now.
